name: lastquakes
description: "An application providing near real-time global earthquake monitoring."
publish_to: "none"

version: 1.0.3+4

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  http: ^1.3.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  url_launcher: ^6.3.1
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  font_awesome_flutter: ^10.8.0
  flutter_map_marker_cluster: ^8.2.2
  flutter_local_notifications: ^19.0.0
  share_plus: ^12.0.1
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.3
  screenshot: ^3.0.0
  introduction_screen: ^4.0.0
  meta: ^1.17.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  fake_async: ^1.3.3
  http_mock_adapter: ^0.6.1
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - LICENSE
    - assets/splash/
