name: lastquake
description: "An application providing near real-time global earthquake monitoring."
# The following line prevents the package from being accidentally published to

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.

# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.

# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 6.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  http: ^1.3.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  url_launcher: ^6.3.1
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  geolocator: ^14.0.0
  font_awesome_flutter: ^10.8.0
  flutter_map_marker_cluster: ^1.4.0
  flutter_local_notifications: ^19.0.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  share_plus: ^10.1.4   
  package_info_plus: ^8.3.0 
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.3
  screenshot: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  fake_async: ^1.3.3
  http_mock_adapter: ^0.6.1
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
